baseURL = 'https://leocoyere.github.io/gohugo/'
languageCode = 'en-us'
title = 'Mon blog perso'
theme = 'ananke'

[params]
description = "Un blog personnel sur Github Pages & Hugo"
logo = "/gohugo/images/home.svg"